### ISSUE TITLE
Отображение текстовых полей на iPhone

### ISSUE THREAD

**Issue by ExEr7um** [DreamSites/dreamsites.github.io#6]
Текстовые поля «Ваше имя» и «Ваш электронный адрес» отображаются неправильно. Они должны находиться посередине, а упираются в правый край.
###Решение
Один из вариантов решения — заменить тэг `<input>` на `<textarea>`.

**Comment by ExEr7um** [comment]
Проблему пофиксил. Для это в `main.css` в версию для мобильных устройств были добавлены строки:
```css
.input {
  width: 90% !important;
  float: right;
  margin-right: 5%;
}
```
